import type { MoonDay } from './types';

export const TAINUI_CALENDAR: Record<number, MoonDay> = {
  1: {
    name: 'Whiro',
    pronunciation: 'Fee-ro',
    energy: 'Low',
    goodFor: ['Rest', 'Reflection', 'Weeding', 'Cleaning up'],
    avoidFor: ['New projects', 'Planting', 'Fishing'],
    desc: 'New moon. Low energy — ideal time to reflect, weed, and clean up.',
  },
  2: {
    name: 'Tirea',
    pronunciation: 'Tee-reh-ah',
    energy: 'Low',
    goodFor: ['Observation', 'Light tasks', 'Planning'],
    avoidFor: ['Major decisions'],
    desc: 'The first faint crescent appears. Energy is still building.',
  },
  3: {
    name: 'Hoata',
    pronunciation: 'Ho-ah-tah',
    energy: 'Moderate',
    goodFor: ['Planting', 'Fishing', 'Gathering materials'],
    avoidFor: ['Signing contracts'],
    desc: 'Favourable day for planting and fishing.',
  },
  4: {
    name: 'Ōuenuku',
    pronunciation: 'Oh-oo-eh-noo-koo',
    energy: 'High',
    goodFor: ['Working', 'Eeling', 'Planting kūmara', 'Soil preparation'],
    avoidFor: ['Idleness'],
    desc: 'Excellent day for working and eeling.',
  },
  5: {
    name: 'Ōkoro',
    pronunciation: 'Oh-ko-ro',
    energy: 'Moderate',
    goodFor: ['Gardening', 'Eeling', 'Afternoon tasks'],
    avoidFor: ['Heavy labour in the morning'],
    desc: 'Good day for gardening and eeling.',
  },
  6: {
    name: 'Tamatea-ā-hotu',
    pronunciation: 'Tah-mah-teh-ah aa ho-too',
    energy: 'Moderate',
    goodFor: ['Weather watching', 'Flexible planning', 'Indoor tasks'],
    avoidFor: ['Ocean travel', 'Long journeys'],
    desc: 'Moderate energy — weather conditions are variable.',
  },
  7: {
    name: 'Tamatea-ā-ngana',
    pronunciation: 'Tah-mah-teh-ah aa ngah-nah',
    energy: 'Low',
    goodFor: ['Stay home', 'Indoor repairs'],
    avoidFor: ['Ocean travel', 'Fishing', 'Long journeys'],
    desc: 'First quarter — turbulent and changing weather and sea.',
  },
  8: {
    name: 'Tamatea-aio',
    pronunciation: 'Tah-mah-teh-ah ah-ee-oh',
    energy: 'Moderate',
    goodFor: ['Food gathering', 'Planting', 'Coastal work'],
    avoidFor: ['Risk taking'],
    desc: 'Conditions improve — a good day to gather food or plant.',
  },
  9: {
    name: 'Tamatea-kai-ariki',
    pronunciation: 'Tah-mah-teh-ah kai ah-ree-kee',
    energy: 'Low',
    goodFor: ['Caution', 'Preparation', 'Checking conditions'],
    avoidFor: ['New ventures', 'Sea travel'],
    desc: 'Final Tamatea day — unpredictable weather.',
  },
  10: {
    name: 'Huna',
    pronunciation: 'Hoo-nah',
    energy: 'Low',
    goodFor: ['Spiritual work', 'Prayer', 'Quiet reflection'],
    avoidFor: ['Fishing', 'Planting', 'Harvesting'],
    desc: 'The moon phase where some food products are vulnerable or hidden.',
  },
  11: {
    name: 'Ariroa',
    pronunciation: 'Ah-ree-ro-ah',
    energy: 'Moderate',
    goodFor: ['Spearing eels', 'Light gardening', 'Fishing'],
    avoidFor: ['Passive rest'],
    desc: 'Good day for spearing eels and light gardening.',
  },
  12: {
    name: 'Maure',
    pronunciation: 'Mow-ree',
    energy: 'High',
    goodFor: ['Planting', 'Fishing', 'Community work', 'All food gathering'],
    avoidFor: ['Nothing major'],
    desc: 'Favourable for both planting and fishing.',
  },
  13: {
    name: 'Māwharu',
    pronunciation: 'Maa-fah-roo',
    energy: 'High',
    goodFor: ['Crayfishing', 'Planting', 'Planting root crops'],
    avoidFor: ['Inaction'],
    desc: 'Excellent day for crayfishing and planting.',
  },
  14: {
    name: 'Ōhua',
    pronunciation: 'Oh-hoo-ah',
    energy: 'High',
    goodFor: ['Working the land', 'Fishing', 'Planting', 'Harvest preparation'],
    avoidFor: ['Procrastination'],
    desc: 'Productive day for working on the land or sea.',
  },
  15: {
    name: 'Atua',
    pronunciation: 'Ah-too-ah',
    energy: 'Low',
    goodFor: ['Prayer', 'Ceremony', 'Sacred observance'],
    avoidFor: ['Fishing', 'Planting', 'Food gathering', 'All work'],
    desc: 'Historically considered a poor day for food gathering.',
  },
  16: {
    name: 'Turu',
    pronunciation: 'Too-roo',
    energy: 'Moderate',
    goodFor: ['Collecting seafood', 'Coastal gathering', 'Earth gathering'],
    avoidFor: ['Major decisions'],
    desc: 'A day to collect food from the sea and earth.',
  },
  17: {
    name: 'Rākaunui',
    pronunciation: 'Raa-kow-noo-ee',
    energy: 'Peak',
    goodFor: ['Planting', 'Harvesting', 'Deep sea fishing', 'Ceremonies', 'Important meetings'],
    avoidFor: ['Eeling'],
    desc: 'Full moon (also known as Ōturu) — high energy, optimal for planting and harvesting.',
  },
  18: {
    name: 'Rākaumatohi',
    pronunciation: 'Raa-kow-mah-to-hee',
    energy: 'High',
    goodFor: ['Fishing', 'Planting kūmara', 'Outdoor work'],
    avoidFor: ['Night eeling'],
    desc: 'A fine day — the moon begins its waning phase.',
  },
  19: {
    name: 'Takirau',
    pronunciation: 'Tah-kee-row',
    energy: 'High',
    goodFor: ['Morning tasks', 'Planting', 'Fishing', 'Strategic planning'],
    avoidFor: ['Afternoon rest'],
    desc: 'Favourable weather during the morning.',
  },
  20: {
    name: 'Oike',
    pronunciation: 'Oh-ee-keh',
    energy: 'Moderate',
    goodFor: ['Afternoon fishing', 'Eeling', 'Garden work', 'Acts of reciprocity'],
    avoidFor: ['Morning exertion'],
    desc: 'Afternoon becomes favourable — a time for reciprocity.',
  },
  21: {
    name: 'Korekore-te-whiwhia',
    pronunciation: 'Ko-reh-ko-reh teh fee-fee-ah',
    energy: 'Low',
    goodFor: ['Rest', 'Relaxation', 'Family time'],
    avoidFor: ['Fishing', 'Planting', 'Important work'],
    desc: 'Low energy — a time to relax.',
  },
  22: {
    name: 'Korekore-te-rawea',
    pronunciation: 'Ko-reh-ko-reh teh rah-weh-ah',
    energy: 'Low',
    goodFor: ['Quiet reflection', 'Spiritual practice', 'Teaching'],
    avoidFor: ['Fishing', 'Planting'],
    desc: 'Low energy — continue resting.',
  },
  23: {
    name: 'Korekore-hahani',
    pronunciation: 'Ko-reh-ko-reh hah-hah-nee',
    energy: 'Low',
    goodFor: ['Light fishing preparation', 'Community connection', 'Gentle gardening'],
    avoidFor: ['Strenuous work'],
    desc: 'The beginning of productive fishing days (also known as Korekore-piri-ki-ngā-Tangaroa).',
  },
  24: {
    name: 'Tangaroa-ā-mua',
    pronunciation: 'Tah-ngah-ro-ah aa moo-ah',
    energy: 'High',
    goodFor: ['Fishing', 'Ocean activities', 'Water ceremonies', 'Coastal work'],
    avoidFor: ['Inland tasks'],
    desc: 'Excellent period for fishing.',
  },
  25: {
    name: 'Tangaroa-ā-roto',
    pronunciation: 'Tah-ngah-ro-ah aa ro-toh',
    energy: 'High',
    goodFor: ['Inshore fishing', 'Shellfish gathering', 'River fishing'],
    avoidFor: ['Deep sea'],
    desc: 'Highly productive day for fishing.',
  },
  26: {
    name: 'Tangaroa-kiokio',
    pronunciation: 'Tah-ngah-ro-ah kee-oh-kee-oh',
    energy: 'Peak',
    goodFor: ['Fishing', 'Eeling', 'Seafood harvest', 'Feast preparation'],
    avoidFor: ['Wasting food'],
    desc: 'A day marked by a misty land aspect (also known as Tangaroa-tahi).',
  },
  27: {
    name: 'Ōtāne',
    pronunciation: 'Oh-taa-neh',
    energy: 'High',
    goodFor: ['Eeling at night', 'Planting', 'Garden blessing'],
    avoidFor: ['Nothing major'],
    desc: 'Waning crescent — great night for eeling.',
  },
  28: {
    name: 'Ōrongonui',
    pronunciation: 'Oh-ro-ngo-noo-ee',
    energy: 'High',
    goodFor: ['Whitebait fishing', 'Planting', 'Community feasts', 'Celebrations'],
    avoidFor: ['Solitude'],
    desc: 'Favourable — whitebait (īnanga) migrate.',
  },
  29: {
    name: 'Mauri',
    pronunciation: 'Mow-ree',
    energy: 'Low',
    goodFor: ['Morning tasks', 'Food preservation', 'Completing work'],
    avoidFor: ['New ventures'],
    desc: 'Low energy — moon darkness sets in.',
  },
  30: {
    name: 'Mutuwhenua',
    pronunciation: 'Moo-too-feh-noo-ah',
    energy: 'Low',
    goodFor: ['Completion', 'Fasting', 'Ceremony', 'Releasing the old'],
    avoidFor: ['Beginnings', 'Purchases', 'Food gathering'],
    desc: 'Exceedingly quiet day as the lunar cycle concludes and energy resets (also known as Ōmutu).',
  },
};
